server.port=${PORT:10000}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.hikari.connection-timeout=120000
spring.datasource.hikari.validation-timeout=120000
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.max-lifetime=600000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.security.user.enabled=false
